Purego
tractordev/toolkit-go pull request #6
Opened 2024-09-17 14:45 UTC by gysddn

This is a somewhat aggressive refactor of the current `cgo` bridge. 

So far, most, almost all, functions calls have been integrated to `purego`.
If the end goal is to get rid of `cgo` altogether, this is the todo list:

- [ ]  Locate library files dynamically.
- [ ] Make sure the strings passed to purego are [null terminated](https://pkg.go.dev/github.com/jwijenbergh/purego#hdr-Memory-RegisterFunc).
- [ ] Handle memory of strings in general
- [ ] Handle callbacks in purego.
- [ ] Go through every C.* call and update them to purego (i.e C.CString).
- [ ] Remove cgo types

2024-09-18 19:28 UTC, gysddn commented
About:

> - [ ] Remove cgo types

If removing `cgo` is not a very strict requirement, I'd like to point out that it provides the types which in turn allows type checking on pointers, that wouldn't otherwise be possible (to my knowledge) in a `purego` only configuration.

I can, of course, convert them into `purego` only calls but I wanted to ask for an input about this @progrium before doing so.

Purego with cgo:

```go
    GtkWidgetShowAll                          func (widget *C.GtkWidget)
```

Purego only:

```go
    GtkWidgetShowAll                          func (widget unsafe.Pointer)
```

2024-09-20 22:17 UTC, progrium commented
> About:
> 
> > * [ ]  Remove cgo types
> 
> If removing `cgo` is not a very strict requirement, I'd like to point out that it provides the types which in turn allows type checking on pointers, that wouldn't otherwise be possible (to my knowledge) in a `purego` only configuration.
> 
> I can, of course, convert them into `purego` only calls but I wanted to ask for an input about this @progrium before doing so.
> 
> Purego with cgo:
> 
> ```go
>     GtkWidgetShowAll                          func (widget *C.GtkWidget)
> ```
> 
> Purego only:
> 
> ```go
>     GtkWidgetShowAll                          func (widget unsafe.Pointer)
> ```

Thanks for asking for clarification here. We do have a hard requirement to remove CGO so I am ok with `unsafe.Pointer` internally. If its exposed to the user, we'll do something extra, but I'm pretty sure it's not. Is that correct?

2024-09-22 09:58 UTC, gysddn commented
Last commit should be "GdkRectangle" not "GdkGeometry", my bad there 😅
Don't want to force-push while in review

2024-09-22 13:31 UTC, gysddn commented
> Thanks for asking for clarification here. We do have a hard requirement to remove CGO so I am ok with `unsafe.Pointer` internally. If its exposed to the user, we'll do something extra, but I'm pretty sure it's not. Is that correct?

Correct. Only exposed types are structs that hold pointers to those types, which are hidden away, so changing them didn't break anything.

2024-09-24 16:41 UTC, gysddn commented
I have tested the API after the last change and reported the problems I found as issues. Other than that, the PR is ready for review. @progrium

2024-09-24 19:24 UTC, progrium requested changes
Looks good just some cosmetic changes and then I'll merge.

2024-09-24 19:24 UTC, progrium commented on desktop/linux/linux.go
> +type GdkGeometry struct {
Even though these represent C structs, we can name fields whatever we want. Let's use Go naming conventions.

2024-09-24 19:24 UTC, progrium commented on desktop/linux/linux.go
> +	GTK_WINDOW_TOPLEVEL = iota
Also for constants, let's keep using Go naming conventions (no all caps, no underscores, ...)

2024-09-24 19:24 UTC, progrium commented on desktop/linux/linux.go
> +	//TODO indentation
yes lets clean up indentation

2024-09-25 10:26 UTC, gysddn commented
Also added function comment docs to denote the actual types of unsafe.Pointers, and to document functions in general.

2024-09-27 10:03 UTC, gysddn commented
@progrium I have cleaned up the file and formatted with proper indentation.
PR is ready for review.

I have a commit for app indicators and working on the handling of `SetSize` (#8) which is partially ready. But I didn't want to make this PR more crowded so I'm planning to submit them as separate PRs after this one is merged.

2024-10-08 05:40 UTC, merged